### ISSUE TITLE
/bin/sh points to dash, not bash: failures on ubuntu

### ISSUE THREAD

**Issue by wdconinc** [KATRIN-Experiment/Kassiopeia#10]
The shell scripts `kasperenv.sh` and `create_kasper_user_directory.sh` have as top line `#!/bin/sh` but assume that that points to bash. This is not the case on Ubuntu (regardless of the wisdom of that choice, it's a major distribution). Resulting [bashisms](https://wiki.ubuntu.com/DashAsBinSh) are presents in the following script lines (some fail execution, some just result in confusing output).

#### In `kasperenv.sh`

`export PATH=${KASPER_INSTALL_BIN}:${PATH//${OLD_PATH}/}` could be `export PATH=${KASPER_INSTALL_BIN}:$(echo $PATH | sed 's/${OLD_PATH}//g')`

`echo -e` should be `printf`

`function` is redundant when followed by `_kafit_krypton_auto()`

`COMPREPLY=(` array is not POSIX compliant and may need to be split off into a separate script with `[ ! -z "${BASH}" ] && . kasper-krypton.bash`.

#### In `create_kasper_user_directory.sh`

`source $T_KASPERSYS/bin/kasperenv.sh` should be `. $T_KASPERSYS/bin/kasperenv.sh`

`echo "#!/bin/sh" > $T_KASPERSYS/bin/kasperenv.sh` prevents appending in case of multiple calls to `create_kasper_user_directory.sh`

All but the COMREPLY bash-completion targets are easy enough to fix. The bash-completion target needs guidance from devs.

**Comment by zykure** [comment]
Thanks for pointing out this issue and providing the fix!
