### ISSUE TITLE
Need to define `_GNU_SOURCE`?

### ISSUE THREAD

**Issue by nsoblath** [KATRIN-Experiment/Kassiopeia#29]
I just pulled v3.7.2 and tried a build on my mac (Mojave, compiler info below) and ran into this error:

```
In file included from /Users/obla999/Software/Kassiopeia/Kassiopeia/Kommon/Core/Utility/KMessage.cxx:9:
In file included from /usr/local/include/boost/stacktrace.hpp:15:
In file included from /usr/local/include/boost/stacktrace/frame.hpp:20:
In file included from /usr/local/include/boost/stacktrace/safe_dump_to.hpp:217:
/usr/local/include/boost/stacktrace/detail/collect_unwind.ipp:33:2: error: "Boost.Stacktrace requires
      `_Unwind_Backtrace` function. Define `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if
      _Unwind_Backtrace is available without `_GNU_SOURCE`."
#error "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `_GNU_SOURCE` macro or `BOOST_STACKTR...
 ^
1 error generated.
```

Compiler info reported by CMake:
```
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
```

**Comment by nsoblath** [comment]
I tried defining each of those variables in when configuring with CMake, and I got the following warnings from CMake:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    _GNU_SOURCE
```

And similarly for the other suggested macro.

Both times, the build still didn't work.

**Comment by zykure** [comment]
I found this (on Boost 1.73+): https://github.com/boostorg/stacktrace/commit/b5e2058ec59577c1d3365955fbe490357958f8bc

It should define `_GNU_SOURCE` automatically I guess, and I don't see how it doesn't work even if you define it manually. You could probably add a `#define _GNU_SOURCE` in `KMessage.cxx` before the boost includes and see if that fixes it? Which Boost version are you using?

Alternatively, we could disable the Boost stacktrace for MacOS and use the old (POSIX?) implementation that's used when Boost is not available. I just added the Boost stacktrace because it gives more information about the source files.

**Comment by pslocum** [comment]
I compiled 3.7.2 from a clean clone on Ubuntu 18.04.4 with Boost 1.69,
cmake output below.  It runs correctly.

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using compiler GNU 7.5.0
-- Building Kasper v3.5.90 (30590)
-- Git revision is master+cf997c1 (last commit: Thu May 7 10:22:39 2020
-0400)
-- Setting build type to 'RelWithDebInfo' as none was specified.
Kassiopeia requires GSL to be enabled in Kasper (activated automatically)
-- Kasper module enabled: Kommon v1.4.0 (10400)
-- Could NOT find LOG4CXX (missing: LOG4CXX_LIBRARY LOG4CXX_INCLUDE_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found GSL: /usr/local/include (found version "2.5")
-- Kasper module enabled: KGeoBag v3.7.0 (30700)
-- Kasper module enabled: KEMField v3.7.0 (30700)
-- Kasper module enabled: Kassiopeia v3.7.0 (30700)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/penny/Kassiopeia/cbuild

**Comment by nsoblath** [comment]
Defining `_GNU_SOURCE` IN `KMessage.h` worked.  I will try defining it in the .cxx file instead.  Once that test is complete, I'll make a PR for this issue.
