### ISSUE TITLE
ROOT version mismatch in Docker Container

### ISSUE THREAD

**Issue by renereimann** [KATRIN-Experiment/Kassiopeia#30]
Pulling and starting a bash shell in the katrinexperiment/kassiopeia docker image works without problems. Once in the shell the kasperenv.sh is executed automatically. If I than invoke `Kassiopeia ./config/Kassiopeia/Examples/DipoleTrapSimulation.xml` or simply just invoking `Kassiopeia` I get the error message `Kassopeia: error while loading shared libraries: libCore.so.6.20: cannot open shared object file: No such file or directory`. A check with `ldd bin/Kassiopeia` shows that there are a lot of shared libraries which can not be found. We found similar shared libraries here: `/usr/lib64/root/libCore.so.6.18`. It seems that all missing libraries are in the `/usr/lib64/root` folder and have the extension *.so.6.18 instead of *.so.6.20. I have the same problem with docker container :3.7.1 and :3.7.2.

**Comment by zykure** [comment]
Hi and thanks for posting this issue. I guess that this is related to Docker's caching mechanisms, where the build layer is probably outdated (and still has ROOT 6.18) while the runtime layer was built against ROOT 6.20. I can reproduce the problem on my local system, so apologies for not testing it fully. I will see about fixing this as soon as possible.

**Comment by zykure** [comment]
This should be fixed now in the 3.7.2 release.

**Comment by renereimann** [comment]
it works, thanks
