### ISSUE TITLE
Inconsistent Treatment of Installation Directories

### ISSUE THREAD

**Issue by nsoblath** [KATRIN-Experiment/Kassiopeia#32]
In KasperDefaults.cmake we find two places where installation directories are dealt with.  The first block is at lines 49-57:

```
    set_path(INCLUDE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/include" "Install directory for headers")
    set_path(LIB_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib" "Install directory for libraries")
    set_path(BIN_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/bin" "Install directory for binaries")
    set_path(CONFIG_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/config" "Install directory for config files")
    set_path(DATA_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/data" "Install directory for data files")
    set_path(SCRATCH_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/scratch" "Directory for temporary files")
    set_path(OUTPUT_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/output" "Directory for output files")
    set_path(CACHE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/cache" "Directory for cache files")
    set_path(LOG_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/log" "Directory for log files")
```

The second block is at lines 175-183:

```
    set( ${PROJECT_NAME}_INCLUDE_INSTALL_DIR ${CMAKE_INSTALL_INCLUDEDIR} )
    set( ${PROJECT_NAME}_LIB_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR} )
    set( ${PROJECT_NAME}_BIN_INSTALL_DIR ${CMAKE_INSTALL_BINDIR} )
    set( ${PROJECT_NAME}_CONFIG_INSTALL_DIR ${CONFIG_INSTALL_DIR}/${PATH} )
    set( ${PROJECT_NAME}_DATA_INSTALL_DIR ${DATA_INSTALL_DIR}/${PATH} )
    set( ${PROJECT_NAME}_SCRATCH_INSTALL_DIR ${SCRATCH_INSTALL_DIR}/${PATH} )
    set( ${PROJECT_NAME}_OUTPUT_INSTALL_DIR ${OUTPUT_INSTALL_DIR}/${PATH} )
    set( ${PROJECT_NAME}_LOG_INSTALL_DIR ${LOG_INSTALL_DIR}/${PATH} )
    set( ${PROJECT_NAME}_CACHE_INSTALL_DIR ${CACHE_INSTALL_DIR}/${PATH} )
```

In the first block we create `[type]_INSTALL_DIR` for all nine types (includes, libs, etc). 

In the second block, however, things are not consistent.  Includes, libs, and bins are re-defined based on the `CMAKE_INSTALL_[TYPE]DIR` variables (which were defined using the `GNUInstallDirs` module back at line 11).  The other six types are defined by adding the `PATH` variable (a macro argument) to the corresponding `[type]_INSTALL_DIR` variable.

As a consequence, the way that the installation directories are controlled is inconsistent and undocumented.  And the variables `INCLUDE_INSTALL_DIR`, `LIB_INSTALL_DIR`, and `BIN_INSTALL_DIR` are unused (and made it more difficult to debug things before I figured out what's really going on).

It would be great if the system for controlling the directories were consistent, or at least well documented and free of unused variables.

**Comment by zykure** [comment]
Sorry for the troubles and thanks for pointing out this issue.

This is updated in the latest release 3.7.4. The `${PROJECT_NAME}_*_INSTALL_DIR` now use the `*_INSTALL_DIR` definitions from the top of KasperDefaults.cmake. The kasperenv.sh script was updated accordingly. This may not be the best solution, but the definitions are now consistent.

**Comment by zykure** [comment]
It seems that there are more paths defined and used elsewhere, which I had missed before. Most notably this leads to problems on systems where `lib64` is used instead of `lib` to install libraries. This is the case for example on CentOS 7.

**Comment by zykure** [comment]
Another update in commit 274cb43b
