### ISSUE TITLE
Error in the calculation of x_loc[2]

### ISSUE THREAD

**Issue by zhufa07** [KATRIN-Experiment/Kassiopeia#38]
https://github.com/KATRIN-Experiment/Kassiopeia/blob/9cf2f80c8382638990cad93d9ee53373e9b62292/KEMField/Source/BoundaryIntegrals/Electrostatic/Analytic/src/KElectrostaticAnalyticTriangleIntegrator.cc#L114

To obtain the correct value for x_loc[2], the length of the edge along n2 of the triangle needs to be used instead of the height b.

**Comment by zykure** [comment]
Thanks for reporting the issue, but I think the code is correct. The parameters a,b of the triangle correspond to the lengths of its sides along n1,n2:

https://github.com/KATRIN-Experiment/Kassiopeia/blob/9cf2f80c8382638990cad93d9ee53373e9b62292/KEMField/Source/Surfaces/include/KTriangle.hh#L100

 How did you find this issue, was there a problem in the calculation?

**Comment by zhufa07** [comment]
I was trying to replicate the formula for the analytical solution of the integration, from the paper "Methodology and application of high performance electrostatic field simulation in the KATRIN experiment", p110-111. But my analytical solution was not identical when I permutated the order of the nodes of my triangle. According to the paper, b is the height of the triangle, so the calculation of x_loc[2], or x_3 in the paper is not correct.

**Comment by jpbarrett** [comment]
Its been a while since I have looked through this code but there has been a good deal of validation done on the analytic triangle integrator (against a few different numerical integration techniques and multipole expansion) so it would be surprising to find such a fundamental error here. At first glance it doesn't look to me like there is any disagreement between TJ's thesis and the code, just a minor difference in indexing/naming convention, where x_1 = x_loc[0], x_2 = x_loc[1], and x_3 = x_loc[2].

**Comment by zykure** [comment]
Thanks for the explanation. It looks like there's some inconsistency in the equations 78 and 80 with the definition of b in the thesis vs. in the code. I don't know if this is just a typo or if the code had this issue too but was fixed, but either way it looks like the current KEMField code is correct.

The equations for x_3 and y_2 need to be modified when defining b as the height of the triangle vs. the length of the n2 side. Eq. A.80 in the thesis is correct for the first definition, but also differs from the code where b is defined as the length.

**Comment by jpbarrett** [comment]
Ah ok, I see the trouble now. Yes, definitely the code is correct, in which 'fB' is the length of the side associated with fN2 (in fact I don't recall it ever having any other meaning) and is not the height of the triangle as mentioned in the caption of figure A.2. Actually, apart from the definition of b within the caption of A.2 i don't see it defined anywhere else, so simply changing of definition of 'b' (from height to side length at this spot in his thesis) ought to suffice to match the code's implementation.

**Comment by zhufa07** [comment]
I see, thank you for the clarification!
