### ISSUE TITLE
Could not find load file ON when setting up Kassiopeia with VTK

### ISSUE THREAD

**Issue by mcclaindavid** [KATRIN-Experiment/Kassiopeia#5]
When attempting to set up Kassiopeia with VTK an issue arises where it attempts to include the file "ON"  whenever kasper_find_vtk is called as shown in the first image. The second image shows the kasper_find_vtk macro setting VTK_USE_FILE to ON and then including it.
![2-22-19-001](https://user-images.githubusercontent.com/48832399/54840706-8fefa580-4c9b-11e9-91d0-469b1f022669.png)
![2-22-19-002](https://user-images.githubusercontent.com/48832399/54840710-9251ff80-4c9b-11e9-81ce-e6bf88a1cf5f.png)

**Comment by buzinsky** [comment]
Hi,
This is a little tricky to debug as I am not running Ubuntu. Just to make sure you are doing the install correctly, vtk should be turned on via ccmake like in http://katrin-experiment.github.io/Kassiopeia/compiling.html#, or by modifying the CMakeCache.txt directly. The variable "KASPER_USE_VTK" should be ON, but I didn't think it should look for a file called "ON".

If that doesn't help, you should verify the integrity of the vtk install, (ie it is in your path/ library path). If you installed vtk from source, as opposed to apt-get, the paths may be missing vtk.

Let me know if it persists

**Comment by zykure** [comment]
Fixed upstream.

This issue is related to improper use of the FindVTK CMake macro, where `VTK_USE_FILE` is not set in older versions (pre-6.x). Also see https://vtk.org/Wiki/VTK/Tutorials/CMakeListsFile
