### ISSUE TITLE
KMagnetostaticFieldmapBuilder and KMagneticSuperpositionField now working together

### ISSUE THREAD

**Issue by renereimann** [KATRIN-Experiment/Kassiopeia#57]
It is currently not possible to calculate the magnetic field using the KMagnetostaticFieldmapBuilder giving a KMagneticSuperpositionField as the field. The reason behind this is that KMagnetostaticFieldmapBuilder assumes a KMagnetostaticField however KMagneticSuperpositionField is a KMagneticField and can have components that are not static. 

There are several ways to make this combinable.

1. A KMagnetostaticSuperpositionField can be defined which is both a superposition and static.
2. The functionality of the KMagnetostaticFieldmapBuilder can be extended to work also for non-static fields by providing a time at which the field should be calculated.

**Comment by zykure** [comment]
I would opt for the second solution and extend the KMagnetostaticFieldmap(Builder) functionality accordingly.

When it was implemented there was no need for time-dependent fields, but it would be easy to implement this. The internal calls to the field solver already support a time parameter, so this really just boils down to adding a builder parameter that is passed on to the field map calculator, and changing the internal field object to KMagneticField.

**Comment by renereimann** [comment]
I looked through the code and to me it appears that the `KMagfieldMapVTK`, `KLinearInterpolationMagfieldMapVTK`, `KCubicInterpolationMagfieldMapVTK`, and `KMagnetostaticFieldmap `do not need any change. They are used to read in VTI files and as a VTI file will not have time dependence stored in it, also the imported field will still be magnetostatic. Thus also the `KMagnetostaticFieldmapBuilder `will not need any update.
Changes are needed in `KMagnetostaticFieldmapCalculator `and `KMagnetostaticFieldmapCalulatorBuilder`.
`KMagnetostaticFieldmapCalculator` needs an additional member variable `double fTime`, a `void SetTime` function and the `AddMagneticField` needs to accept `KMagneticField` instead of `KMagnetostaticField`. Within `KMagnetostaticFieldmapCalculator` the calls `KMagnetostaticField->MagneticField(KPosition(tPoint))` and `KMagnetostaticField->MagneticGradient(KPosition(tPoint))`  need to include the time as second argument. The MagneticField(position, time)  and MagneticGradient(position, time) are implemented for all `KMagneticFields`.

I am working on a pull request in the next hours.
