### ISSUE TITLE
Invalid Include File

### ISSUE THREAD

**Issue by nsoblath** [KATRIN-Experiment/Kassiopeia#7]
In `KSRootBuilder.h` the file `KEMToolbox.h` is included.  However, that latter file is not used and isn't included in the CMake installation.  It should be removed as an include in `KSRootBuilder.h`.  This doesn't make much of a difference in the normal build, but I was building it in a somewhat unusual way and it became a problem.

**Comment by zykure** [comment]
Fixed upstream.
