### ISSUE TITLE
Physical constants epoch not working when using Kassiopeia as an external library

### ISSUE THREAD

**Issue by 2xB** [KATRIN-Experiment/Kassiopeia#72]
> Regarding the selection of the physical constants epoch, we do not presently have a known way of doing the flag selection from P8 through the ```#ifndef..#endif``` logic in prebuilt images (the combined build crashes, even with cmake flags specified).  As a temporary workaround we have hard-wired the 2006 constants in our local fork of Kass.  Would it be possible to somehow alter the ```#ifndef..#endif``` logic, or remove it and hard-wire the 2021 constants?  We can then update to the 2021 constants on the P8 side, although possibly not quite instantaneously.  Alternatively, we can explore the cmake flag usage further, which might also be useful.  Maybe that should have worked in the first place.

_Originally posted by @pslocum in https://github.com/KATRIN-Experiment/Kassiopeia/issues/71#issuecomment-1714379658_

**Comment by 2xB** [comment]
While I think #74 would fix this issue, I would like to understand it first to ensure we don't have the same issue in similar form with e.g. `KASPER_USE_GSL` as well. Would it be possible to get the error message you observe @pslocum ?

**Comment by pslocum** [comment]
Yes, I will forward the error message.  Thanks for looking into this.

**Comment by pslocum** [comment]
Below is the first indication of an error during our build with the KConst option, even with
`-D KConst_REFERENCE_EPOCH:STRING=2006` in our P8 CMakeLists.txt file.  The error looks as though a value for the flag has not been specified.  It is possible that there is a more appropriate way to specify the option.  But our present workaround is to remove the option, by replacing the file `KConst.h` with `KConst_2006.h` .  


/usr/local/p8/kassiopeia/vDebug4.0.0/include/KConst.h:462:2: error: #error "Unsupported value for KConst_REFERENCE_EPOCH."
  462 | #error "Unsupported value for KConst_REFERENCE_EPOCH."
      |  ^~~~~
In file included from /usr/local/p8/kassiopeia/vDebug4.0.0/include/KTwoVector.hh:4,
                 from /usr/local/p8/kassiopeia/vDebug4.0.0/include/KThreeVector.hh:6,
                 from /usr/local/p8/kassiopeia/vDebug4.0.0/include/KThreeMatrix.hh:4,
                 from /usr/local/p8/kassiopeia/vDebug4.0.0/include/KSElectricField.h:6,
                 from /usr/local/p8/kassiopeia/vDebug4.0.0/include/KSParticle.h:4,
                 from /usr/local/p8/kassiopeia/vDebug4.0.0/include/KSSpaceInteraction.h:5,
                 from /tmp_loc_source/Source/Kassiopeia/LMCFieldCalculator.hh:11,
                 from /tmp_loc_source/Source/Generators/LMCCavitySignalGenerator.hh:20,
                 from /tmp_loc_source/Source/Generators/LMCCavitySignalGenerator.cc:8:
/usr/local/p8/kassiopeia/vDebug4.0.0/include/KConst.h:462:2: error: #error "Unsupported value for KConst_REFERENCE_EPOCH."
  462 | #error "Unsupported value for KConst_REFERENCE_EPOCH."
      |  ^~~~~

**Comment by 2xB** [comment]
I would leave that `-D KConst_REFERENCE_EPOCH:STRING=2006` out of your `CMakeLists.txt`, that is just necessary in case of bugs in Kassiopeia. Anyways it potentially didn't work because of the `:STRING`.

I'm now suggesting to merge the known-to-be-working fix in #75, since it is a valid approach and although it isn't a fix for all similar potential issues in Kassiopeia, it fixes the issue at hand.

**Comment by pslocum** [comment]
Great, this sounds like a good plan.
